apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "dieroll.fullname" . }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: die-roll
spec:
  tls:
  - hosts:
    - {{ .Values.metadata.namespace }}.k8s.sketchdev.io
    secretName: tls-secret
  rules:
  - host: {{ .Values.metadata.namespace }}.k8s.sketchdev.io
    http:
      paths:
        - path: /{{ .Values.appVersion }}(/|$)(.*)
          backend:
            serviceName: {{ template "dieroll.fullname" . }}
            servicePort: {{ .Values.service.externalport }}
        - path: /([ ]*)(.*)
          backend:
            serviceName: {{ template "dieroll.fullname" . }}
            servicePort: {{ .Values.service.externalport }}
